# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-04-03T01:27:49+00:00

from __future__ import annotations

from typing import List, Optional, Union

from fastapi import FastAPI

from .models import Book, BookInput, BooksIdGetResponse, Status, User, UserInput

app = FastAPI(
    title='Khß║úo s├ít API Quß║ún l├╜ Th╞░ viß╗çn (RAML)',
    version='v1',
    description='T├ái liß╗çu n├áy thß╗â hiß╗çn API thiß║┐t kß║┐ d╞░ß╗¢i ─æß╗ïnh dß║íng **RAML**  (RESTful API Modeling Language). ─Éß║╖c tr╞░ng nß╗òi bß║¡t ß╗ƒ ─æß╗ïnh dß║íng n├áy l├á  giß║úm lß║╖p code (DRY) th├┤ng qua viß╗çc hß╗ç thß╗æng m├┤ h├¼nh c├óy endpoints rß║Ñt trß╗▒c quan v├á cung cß║Ñp `traits` c├╣ng `types`.\n',
    servers=[{'url': 'http://localhost:8000/'}],
)


@app.get('/books', response_model=List[Book])
def g_e_t_books(status: Optional[Status] = None) -> List[Book]:
    pass


@app.post('/books', response_model=None, responses={'201': {'model': Book}})
def p_o_s_t_books(body: BookInput) -> Optional[Book]:
    pass


@app.get(
    '/books/{id}', response_model=Book, responses={'404': {'model': BooksIdGetResponse}}
)
def g_e_t_books_id(id: int) -> Union[Book, BooksIdGetResponse]:
    pass


@app.get('/users', response_model=List[User])
def g_e_t_users() -> List[User]:
    pass


@app.post('/users', response_model=None, responses={'201': {'model': User}})
def p_o_s_t_users(body: UserInput) -> Optional[User]:
    pass
