# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-04-03T01:27:49+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class Status(Enum):
    available = 'available'
    borrowed = 'borrowed'


class Book(BaseModel):
    id: int = Field(..., example=1)
    title: str = Field(..., example='Sapiens: L╞░ß╗úc Sß╗¡ Lo├ái Ng╞░ß╗¥i')
    author: str = Field(..., example='Yuval Noah Harari')
    status: Status = Field(..., example='available')


class BookInput(BaseModel):
    title: str
    author: str
    status: Status


class User(BaseModel):
    id: int
    name: str
    email: str


class UserInput(BaseModel):
    name: str
    email: str


class BooksIdGetResponse(BaseModel):
    detail: str
