openapi: 3.1.0
info:
  title: Demo Library Management OpenAPI
  description: Demo quản lý sách và người dùng theo chuẩn OpenAPI.
  version: 1.0.0
paths:
  /books:
    get:
      summary: Lấy danh sách sách
      description: Trả về danh sách toàn bộ sách trong thư viện.
      operationId: get_books_books_get
      parameters:
      - name: status
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          description: Lọc theo trạng thái sách
          enum:
          - available
          - borrowed
          title: Status
        description: Lọc theo trạng thái sách
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
                title: Response Get Books Books Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      summary: Thêm sách mới vào thư viện
      description: Tạo một bản ghi sách mới và trả về sách vừa lưu.
      operationId: create_book_books_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookBase'
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /books/{id}:
    get:
      summary: Xem chi tiết một sách cụ thể
      description: Tìm kiếm sách dựa theo đường dẫn ID cung cấp.
      operationId: get_book_books__id__get
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          title: Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /users:
    get:
      summary: Lấy danh sách thành viên
      description: Trả về danh sách tất cả các user.
      operationId: get_users_users_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                type: array
                title: Response Get Users Users Get
    post:
      summary: Thêm thành viên mới
      description: Đăng ký user mới và trả về ID.
      operationId: create_user_users_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserBase'
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Book:
      properties:
        title:
          type: string
          title: Title
        author:
          type: string
          title: Author
        status:
          type: string
          title: Status
        id:
          type: integer
          title: Id
      type: object
      required:
      - title
      - author
      - status
      - id
      title: Book
    BookBase:
      properties:
        title:
          type: string
          title: Title
        author:
          type: string
          title: Author
        status:
          type: string
          title: Status
      type: object
      required:
      - title
      - author
      - status
      title: BookBase
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    User:
      properties:
        name:
          type: string
          title: Name
        email:
          type: string
          title: Email
        id:
          type: integer
          title: Id
      type: object
      required:
      - name
      - email
      - id
      title: User
    UserBase:
      properties:
        name:
          type: string
          title: Name
        email:
          type: string
          title: Email
      type: object
      required:
      - name
      - email
      title: UserBase
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
