# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-04-16T09:43:20+00:00

from __future__ import annotations

from typing import List, Optional, Union

from fastapi import FastAPI, Path

from .models import Product, ProductCreate

app = FastAPI(
    title='Swagger Codegen Demo API',
    description='API quản lý Products, dùng để demo tự động sinh Backend FastAPI và kết nối với database.',
    version='1.0.0',
    servers=[
        {'url': 'http://localhost:8000', 'description': 'Local development server'}
    ],
)


@app.get('/products', response_model=List[Product], tags=['Products'])
def get_products(
    name: Optional[str] = None,
    min_price: Optional[float] = None,
    max_price: Optional[float] = None,
) -> List[Product]:
    """
    Lấy danh sách sản phẩm
    """
    pass


@app.post(
    '/products',
    response_model=None,
    responses={'201': {'model': Product}},
    tags=['Products'],
)
def create_product(body: ProductCreate) -> Optional[Product]:
    """
    Tạo sản phẩm mới
    """
    pass


@app.get('/products/{productId}', response_model=Product, tags=['Products'])
def get_product_by_id(product_id: int = Path(..., alias='productId')) -> Product:
    """
    Lấy chi tiết một sản phẩm theo ID
    """
    pass


@app.put('/products/{productId}', response_model=Product, tags=['Products'])
def update_product(
    product_id: int = Path(..., alias='productId'), body: ProductCreate = ...
) -> Product:
    """
    Cập nhật thông tin toàn bộ một sản phẩm
    """
    pass


@app.delete('/products/{productId}', response_model=None, tags=['Products'])
def delete_product(product_id: int = Path(..., alias='productId')) -> None:
    """
    Xóa một sản phẩm
    """
    pass
