# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-04-16T09:43:20+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Product(BaseModel):
    id: int = Field(..., description='Mã định danh ID')
    name: str = Field(..., description='Tên sản phẩm')
    price: float = Field(..., description='Giá tiền (thực)')
    stock_quantity: int = Field(..., description='Số lượng còn lại trong kho')


class ProductCreate(BaseModel):
    name: str
    price: float
    stock_quantity: int
