# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-04-10T00:52:01+00:00

from __future__ import annotations

from typing import List, Optional, Union

from fastapi import FastAPI

from .models import (
    BooksGetResponse,
    BooksPostRequest,
    BooksPostResponse,
    UsersPostRequest,
    UsersPostResponse,
)

app = FastAPI(
    title='Khảo sát API Quản lý Thư viện (API Blueprint)',
    version='1.0.0',
    description='Tài liệu này thể hiện API thiết kế dưới định dạng **API Blueprint (phong cách MSON - Markdown Syntax for Object Notation)**. Bạn sẽ nhận thấy sự thân thiện tuyệt đối với con người khi mọi block mô hình hay endpoint đều đọc trơn tru như một bản doc markdown thông thường.\n\n# Group Quản lý Sách (Books)\n\nNhóm Endpoints thao tác liên quan tới sách trong kho.',
    servers=[{'url': 'http://localhost:8000'}],
)


@app.get('/books', response_model=BooksGetResponse)
def lấy_thông_tin_chi_tiết_một_cuốn(status: Optional[str] = None) -> BooksGetResponse:
    """
    Lấy thông tin chi tiết một cuốn
    """
    pass


@app.post(
    '/books', response_model=None, responses={'201': {'model': BooksPostResponse}}
)
def thêm_sách_mới_vào_thư_viện(
    status: Optional[str] = None, id: str = ..., body: BooksPostRequest = None
) -> Optional[BooksPostResponse]:
    """
    Thêm sách mới vào thư viện
    """
    pass


@app.get('/users', response_model=List)
def xem_danh_sách_toàn_bộ_người_dùng() -> List:
    """
    Xem danh sách toàn bộ người dùng
    """
    pass


@app.post(
    '/users', response_model=None, responses={'201': {'model': UsersPostResponse}}
)
def tạo_người_dùng_mới(body: UsersPostRequest = None) -> Optional[UsersPostResponse]:
    """
    Tạo người dùng mới
    """
    pass
