# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-04-03T02:05:17+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Field


class Status(Enum):
    available = 'available'
    borrowed = 'borrowed'


class Book(BaseModel):
    id: float = Field(..., description='Không được để trống', example=1)
    title: str = Field(..., example='Sapiens')
    author: str = Field(..., example='Yuval Noah Harari')
    status: Status


class BookInput(BaseModel):
    title: str = Field(..., example='Nhà Giả Kim')
    author: str = Field(..., example='Paulo Coelho')
    status: str = Field(..., example='borrowed')


class User(BaseModel):
    id: float = Field(..., example=101)
    name: str = Field(..., example='Alice')
    email: str = Field(..., example='alice@example.com')


class UserInput(BaseModel):
    name: str = Field(..., example='Bob')
    email: str = Field(..., example='bob@example.com')


class Books(BaseModel):
    __root__: List


class Users(BaseModel):
    __root__: List


class BooksGetResponse(BaseModel):
    id: float = Field(..., description='Không được để trống')
    title: str
    author: str
    status: Status


class BooksPostRequest(BaseModel):
    title: str
    author: str
    status: str


class BooksPostResponse(BaseModel):
    id: float = Field(..., description='Không được để trống')
    title: str
    author: str
    status: Status


class UsersPostRequest(BaseModel):
    name: str
    email: str


class UsersPostResponse(BaseModel):
    id: float
    name: str
    email: str
