# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-04-10T00:52:01+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Field, RootModel


class Status(Enum):
    available = 'available'
    borrowed = 'borrowed'


class Book(BaseModel):
    id: str = Field(..., description='Không được để trống', example='1')
    title: str = Field(..., example='Sapiens')
    author: str = Field(..., example='Yuval Noah Harari')
    status: Status


class BookInput(BaseModel):
    title: str = Field(..., example='Nhà Giả Kim')
    author: str = Field(..., example='Paulo Coelho')
    status: str = Field(..., example='borrowed')


class User(BaseModel):
    id: str = Field(..., example='101')
    name: str = Field(..., example='Alice')
    email: str = Field(..., example='alice@example.com')


class UserInput(BaseModel):
    name: str = Field(..., example='Bob')
    email: str = Field(..., example='bob@example.com')


class Books(RootModel[List]):
    pass


class Users(RootModel[List]):
    pass


class BooksGetResponse(BaseModel):
    id: str = Field(..., description='Không được để trống')
    title: str
    author: str
    status: Status


class BooksPostRequest(BaseModel):
    title: str
    author: str
    status: str


class BooksPostResponse(BaseModel):
    id: str = Field(..., description='Không được để trống')
    title: str
    author: str
    status: Status


class UsersPostRequest(BaseModel):
    name: str
    email: str


class UsersPostResponse(BaseModel):
    id: str
    name: str
    email: str
